services:
 db:
  image: postgres:15
  container_name: postgres_user
  environment:
   POSTGRES_USER: ${DB_USER}
   POSTGRES_PASSWORD: ${DB_PASSWORD}
   POSTGRES_DB: ${DB_NAME}
  env_file:
   - .env
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data:
